name: ucn_usr_mgm
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  build_runner: ^2.4.4
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  json_annotation: ^4.1.0

dev_dependencies:
  json_serializable: ^6.0.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

